# ------------------------------------- PULL REQUEST LABELS ------------------------------------- #
autolabeler:
  # Conventional Commit Types (https://github.com/commitizen/conventional-commit-types)
  - label: build
    title:
      - '/^build(\(.*\))?(\!)?\:/'
  - label: chore
    title:
      - '/^chore(\(.*\))?(\!)?\:/'
  - label: ci
    title:
      - '/^ci(\(.*\))?(\!)?\:/'
  - label: documentation
    title:
      - '/^docs(\(.*\))?(\!)?\:/'
  - label: enhancement
    title:
      - '/^feat(\(.*\))?(\!)?\:/'
  - label: fix
    title:
      - '/^fix(\(.*\))?(\!)?\:/'
  - label: performance
    title:
      - '/^perf(\(.*\))?(\!)?\:/'
  - label: refactor
    title:
      - '/^refactor(\(.*\))?(\!)?\:/'
  - label: revert
    title:
      - '/^revert(\(.*\))?(\!)?\:/'
  - label: style
    title:
      - '/^style(\(.*\))?(\!)?\:/'
  - label: test
    title:
      - '/^test(\(.*\))?(\!)?\:/'
  # Custom Types
  - label: breaking
    title:
      - '/^[a-z]+(\(.*\))?\!\:/'
template: |
  template: |
  ## What's Changed

  $CHANGES

  **Full Changelog:** [`$PREVIOUS_TAG...v$RESOLVED_VERSION`](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
