[project]
name = "pixi-pack"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
build = "cargo build --release"
test-pixi-pack = "cargo test"
test-extractor = { cmd = "cargo test --manifest-path extractor/Cargo.toml", env = { PIXI_PACK_DEFAULT_VERSION = "1" } }
test = { depends-on = ["test-pixi-pack", "test-extractor"] }

[dependencies]
rust = "1.77.2"
openssl = "3.*"
pkg-config = "*"

[target.linux.dependencies]
compilers = ">=1.7.0"

[feature.test.dependencies]
conda = "*"
micromamba = "*"

[feature.demo.dependencies]
vhs = "*"
[feature.demo.tasks]
demo = "vhs .github/assets/demo/demo-light.tape && vhs .github/assets/demo/demo-dark.tape"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = ["lint", "test"]
demo = { features = ["demo"], no-default-feature = true }
lint = { features = ["lint"], no-default-feature = true }
