[project]
name = "pixi-pack"
version = "0.1.0"
description = "A command line tool to pack and unpack conda environments for easy sharing."
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
build = "cargo build --release"
test = "cargo test"

[dependencies]
rust = "1.77.2"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = ["lint"]
lint = ["lint"]
