[project]
name = "pixi-pack"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
build = "cargo build --release"
test = "cargo test"

[dependencies]
rust = "1.77.2"
openssl = "3.*"
pkg-config = "*"

[target.linux.dependencies]
compilers = ">=1.7.0"

[feature.test.dependencies]
conda = "*"
micromamba = "*"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = ["lint", "test"]
lint = { features = ["lint"], no-default-feature = true }
