[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
local-build-main-pkg = { path = "." }

[package]
name = "local-build-main-pkg"
version = "0.1.0"

[package.build]
# xref: https://github.com/prefix-dev/pixi/issues/6524
backend = { name = "pixi-build-cmake", version = "==0.4.3" }

[package.run-dependencies]
local-build-local-pkg = { path = "./local-pkg" }

[tool.update]
autoupdate-schedule = "never"
