[project]
name = "test-auth"
channels = ["https://repo.prefix.dev/setup-pixi-test", "conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
test = "python -c 'print(\"Hello world!\")'"

[dependencies]
python = "3.9.*"
private-package = "*"
