[project]
channels = ["conda-forge"]
name = "pypi-bdist-packages"
platforms = [
  "osx-arm64",
  "osx-64",
  "linux-64",
  "linux-aarch64",
  "linux-ppc64le",
  "win-64",
]

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
ordered-enum = ">=0.0.9,<0.0.10"

[target.linux-64.pypi-dependencies]
numpy = { url = "https://files.pythonhosted.org/packages/3a/d0/edc009c27b406c4f9cbc79274d6e46d634d139075492ad055e3d68445925/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }
