[project]
name = "test-project"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]

# conda dependencies
[dependencies]
python = "3.11.*"

# extra dependencies from PyPI
[pypi-dependencies]
pyboy = "~=1.6.9"
