[project]
name = "test-project"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
# requires 'psysdl2' which is a source distribution
pyboy = "~=1.6.9"
# wheel
ordered-enum = ">=0.0.9,<0.0.10"
