[project]
channels = ["conda-forge"]
name = "pypi-direct-wheel-packages"
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
numpy = { url = "https://files.pythonhosted.org/packages/3a/d0/edc009c27b406c4f9cbc79274d6e46d634d139075492ad055e3d68445925/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }
