[project]
channels = ["conda-forge"]
name = "pypi-bdist-packages"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
ordered-enum = ">=0.0.9, <0.0.10"
