[project]
channels = ["conda-forge"]
name = "pypi-bdist-packages"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
numpy = ">=2.2.3, <3"
# torch has local version, which is percent encoded on url, it should be decode.
# torch-2.6.0%2Bcpu + torch-2.6.0+cpu
torch = {version = ">=2.2", index = "https://download.pytorch.org/whl/cpu"}

